name: Build Shortcut

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cherri
        run: brew install electrikmilk/cherri/cherri

      - name: Build
        run: |
          cherri breve-saude.cherri --hubsign
          find . -name "*.shortcut" -type f

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: shortcut
          path: "*.shortcut"
